################################################################################
# 自动生成的文件。不要编辑！
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# 此处必须描述包含源文件的每个子目录
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32H7xx_HAL_Driver/Src \
FreeRtos \
FreeRtos/portable \
SCSLib \
my_drivers/LVGL/demos/benchmark/assets \
my_drivers/LVGL/demos/benchmark \
my_drivers/LVGL/demos/keypad_encoder \
my_drivers/LVGL/demos/music/assets \
my_drivers/LVGL/demos/music \
my_drivers/LVGL/demos/stress \
my_drivers/LVGL/demos/widgets/assets \
my_drivers/LVGL/demos/widgets \
my_drivers/LVGL/examples/porting \
my_drivers/LVGL/src/core \
my_drivers/LVGL/src/draw/arm2d \
my_drivers/LVGL/src/draw \
my_drivers/LVGL/src/draw/nxp \
my_drivers/LVGL/src/draw/nxp/pxp \
my_drivers/LVGL/src/draw/nxp/vglite \
my_drivers/LVGL/src/draw/sdl \
my_drivers/LVGL/src/draw/stm32_dma2d \
my_drivers/LVGL/src/draw/sw \
my_drivers/LVGL/src/draw/swm341_dma2d \
my_drivers/LVGL/src/extra/layouts/flex \
my_drivers/LVGL/src/extra/layouts/grid \
my_drivers/LVGL/src/extra/libs/bmp \
my_drivers/LVGL/src/extra/libs/ffmpeg \
my_drivers/LVGL/src/extra/libs/freetype \
my_drivers/LVGL/src/extra/libs/fsdrv \
my_drivers/LVGL/src/extra/libs/gif \
my_drivers/LVGL/src/extra/libs/png \
my_drivers/LVGL/src/extra/libs/qrcode \
my_drivers/LVGL/src/extra/libs/rlottie \
my_drivers/LVGL/src/extra/libs/sjpg \
my_drivers/LVGL/src/extra \
my_drivers/LVGL/src/extra/others/fragment \
my_drivers/LVGL/src/extra/others/gridnav \
my_drivers/LVGL/src/extra/others/ime \
my_drivers/LVGL/src/extra/others/imgfont \
my_drivers/LVGL/src/extra/others/monkey \
my_drivers/LVGL/src/extra/others/msg \
my_drivers/LVGL/src/extra/others/snapshot \
my_drivers/LVGL/src/extra/themes/basic \
my_drivers/LVGL/src/extra/themes/default \
my_drivers/LVGL/src/extra/themes/mono \
my_drivers/LVGL/src/extra/widgets/animimg \
my_drivers/LVGL/src/extra/widgets/calendar \
my_drivers/LVGL/src/extra/widgets/chart \
my_drivers/LVGL/src/extra/widgets/colorwheel \
my_drivers/LVGL/src/extra/widgets/imgbtn \
my_drivers/LVGL/src/extra/widgets/keyboard \
my_drivers/LVGL/src/extra/widgets/led \
my_drivers/LVGL/src/extra/widgets/list \
my_drivers/LVGL/src/extra/widgets/menu \
my_drivers/LVGL/src/extra/widgets/meter \
my_drivers/LVGL/src/extra/widgets/msgbox \
my_drivers/LVGL/src/extra/widgets/span \
my_drivers/LVGL/src/extra/widgets/spinbox \
my_drivers/LVGL/src/extra/widgets/spinner \
my_drivers/LVGL/src/extra/widgets/tabview \
my_drivers/LVGL/src/extra/widgets/tileview \
my_drivers/LVGL/src/extra/widgets/win \
my_drivers/LVGL/src/font \
my_drivers/LVGL/src/hal \
my_drivers/LVGL/src/misc \
my_drivers/LVGL/src/widgets \
my_drivers/User/Src \

